/**
 * Compugamer
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Driver { 
    id?: number;
    dni?: number;
    name?: string | null;
    age?: number;
    licenseNumber?: number;
    busId?: number | null;
}

